### ISSUE TITLE
Increasing the limit for categories

### ISSUE THREAD

**Issue by Ksushis** [JohnGUnderwood/atlas-search-tuner#34]
<img width="1333" alt="Screenshot 2023-11-06 at 3 42 04 PM" src="https://github.com/JohnGUnderwood/atlas-search-tuner/assets/15059473/9c320471-e99f-4fcc-95b4-28c1262beecd">

I wonder what algorithm we're using for categories/facets. For this test dataset I don't have brands showing up and I still want to do facets on them. But there are more than a 1000 brands here... 

To get the data.

git clone https://github.com/Ksushis/grocerystore

mognorestore from terminal

cd grocerystore 
mongorestore <CONNECTION STRING>

You should now have grocery database with items collection with 19564 documents

**Comment by JohnGUnderwood** [comment]
The [latest version](https://github.com/JohnGUnderwood/atlas-search-tuner/tree/v2.0.1) has some improvements for the schema analysis so this is now fixed.

![Screenshot 2023-11-10 at 16 50 00](https://github.com/JohnGUnderwood/atlas-search-tuner/assets/4124456/76e049f9-e8f7-4434-8473-1c5c71a94fee)
